# Homebrew cask for DeepSeekBar 2.0.0.
#
#   brew install --cask https://github.com/andreiteodor97/deepseekbar/raw/main/Casks/DeepSeekBar.rb
#
# Generated by tools/package.sh; that script is the source of truth.
cask "deepseekbar" do
  version "2.0.0"
  sha256 "ef5eced31aaef2ab66fe40cc30d6c32747730eac507c9b3212b13f7f161a5b39"

  url "https://github.com/andreiteodor97/deepseekbar/releases/download/v#{version}/DeepSeekBar-#{version}.zip"
  name "DeepSeekBar"
  desc "Menu bar app for DeepSeek peak/off-peak API pricing and spend"
  homepage "https://github.com/andreiteodor97/deepseekbar"

  livecheck do
    url :url
    strategy :github_latest
  end

  depends_on macos: ">= :ventura"

  app "DeepSeekBar.app"

  zap trash: [
    "~/Library/Application Support/DeepSeekBar",
    "~/Library/Preferences/com.andreiteodor.deepseekbar.plist",
  ]

  caveats <<~EOS
    DeepSeekBar is not notarized. If macOS refuses to open it, allow it once with:
      xattr -dr com.apple.quarantine "#{appdir}/DeepSeekBar.app"
  EOS
end
