#!/bin/bash
#
# Builds the release artifacts into dist/.
#
#   ./tools/package.sh
#
# Produces:
#   dist/DeepSeekBar-<version>.zip            the app, for direct download
#   dist/DeepSeekBar-<version>.dmg            the app, with an /Applications shortcut
#   dist/DeepSeekBar-<version>.zip.sha256     checksums
#   dist/DeepSeekBar-<version>.dmg.sha256
#   dist/DeepSeekBar.rb                       Homebrew cask for this version
#   dist/checksums.txt
#
# The app is ad-hoc signed, not notarized: notarization needs a paid Apple Developer
# account, and this is an unofficial client built by its users. The README tells people
# how to get past Gatekeeper, and `make run` / the Homebrew cask avoid the issue entirely.

set -euo pipefail

DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$DIR"

VERSION="$(cat VERSION | tr -d '[:space:]')"
APP_NAME="DeepSeekBar"
BUNDLE_ID="com.andreiteodor.deepseekbar"
APP="$DIR/build/$APP_NAME.app"
DIST="$DIR/dist"
STAGE="$DIR/build/dmg"

# Where releases live. Derived from the git remote when there is one, so forks and
# renames keep working, with an explicit override for CI.
REPO="${DEEPSEEKBAR_REPO:-}"
if [ -z "$REPO" ]; then
    REPO="$(git config --get remote.origin.url 2>/dev/null \
        | sed -E 's#(git@|https://)github.com[:/]##; s#\.git$##' || true)"
fi
REPO="${REPO:-andreiteodor97/deepseekbar}"
REPO_URL="https://github.com/$REPO"

echo "==> Packaging $APP_NAME $VERSION for $REPO"

./build.sh > /dev/null

if [ ! -d "$APP" ]; then
    echo "error: $APP was not built" >&2
    exit 1
fi

rm -rf "$DIST"
mkdir -p "$DIST"

# ---------------------------------------------------------------- zip
echo "==> Building zip"
# `ditto` rather than `zip`: it preserves the bundle's metadata and symlinks exactly.
ditto -c -k --sequesterRsrc --keepParent "$APP" "$DIST/$APP_NAME-$VERSION.zip"

# ---------------------------------------------------------------- dmg
echo "==> Building dmg"
rm -rf "$STAGE"
mkdir -p "$STAGE"
cp -R "$APP" "$STAGE/"
ln -s /Applications "$STAGE/Applications"
# A plain folder reads best in the Finder window this produces.
cat > "$STAGE/READ ME FIRST.txt" <<'TXT'
DeepSeekBar is not notarized by Apple, so macOS may say it "cannot be opened because
the developer cannot be verified".

To allow it, either:

  1. Right-click DeepSeekBar in Applications and choose Open, then Open again, or
  2. Run this once in Terminal:

       xattr -dr com.apple.quarantine /Applications/DeepSeekBar.app

Then drag DeepSeekBar to Applications and launch it.
TXT

hdiutil create \
    -volname "$APP_NAME $VERSION" \
    -srcfolder "$STAGE" \
    -ov -format UDZO \
    "$DIST/$APP_NAME-$VERSION.dmg" > /dev/null

rm -rf "$STAGE"

# ---------------------------------------------------------------- checksums
echo "==> Computing checksums"
(
    cd "$DIST"
    shasum -a 256 "$APP_NAME-$VERSION.zip" | tee "$APP_NAME-$VERSION.zip.sha256"
    shasum -a 256 "$APP_NAME-$VERSION.dmg" | tee "$APP_NAME-$VERSION.dmg.sha256"
) > "$DIST/checksums.txt"
cat "$DIST/checksums.txt"

# ---------------------------------------------------------------- homebrew cask
echo "==> Writing Homebrew cask"
ZIP_SHA="$(cut -d' ' -f1 < "$DIST/$APP_NAME-$VERSION.zip.sha256")"
# Two heredocs: the body needs shell expansion for version/sha/URL, while the caveats
# block contains Ruby interpolation (`#{appdir}`) that a shell heredoc would eat.
{
    cat <<RUBY
# Homebrew cask for $APP_NAME $VERSION.
#
#   brew install --cask $REPO_URL/raw/main/Casks/$APP_NAME.rb
#
# Generated by tools/package.sh; that script is the source of truth.
cask "deepseekbar" do
  version "$VERSION"
  sha256 "$ZIP_SHA"

  url "$REPO_URL/releases/download/v#{version}/$APP_NAME-#{version}.zip"
  name "$APP_NAME"
  desc "Menu bar app for DeepSeek peak/off-peak API pricing and spend"
  homepage "$REPO_URL"

  livecheck do
    url :url
    strategy :github_latest
  end

  depends_on macos: ">= :ventura"

  app "$APP_NAME.app"

  zap trash: [
    "~/Library/Application Support/$APP_NAME",
    "~/Library/Preferences/$BUNDLE_ID.plist",
  ]

RUBY
    cat <<'RUBY'
  caveats <<~EOS
    DeepSeekBar is not notarized. If macOS refuses to open it, allow it once with:
      xattr -dr com.apple.quarantine "#{appdir}/DeepSeekBar.app"
  EOS
end
RUBY
} > "$DIST/$APP_NAME.rb"

echo
echo "==> Artifacts in dist/:"
ls -lh "$DIST" | tail -n +2
